name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make CXXFLAGS="-std=c++17 -Wall" serial

  macos-build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make CXXFLAGS="-std=c++17 -Wall" serial
